language: python

python:
  - 3.5

env:
  - DJANGO=Django==1.9.7

install:
    - pip3 install -r requirements.txt

script:
    - python3 about_us/manage.py makemigrations
    - python3 about_us/manage.py migrate
