# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('au_about', '0001_initial'),
        ('au_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='abouts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='au_about.About'),
            preserve_default=False,
        ),
    ]
