# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('au_auth', '0003_remove_profile_abouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_abouts',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
