# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('positive_votes', models.IntegerField()),
                ('negative_votes', models.IntegerField()),
            ],
        ),
    ]
