# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('au_auth', '0003_remove_profile_abouts'),
        ('au_about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='au_auth.Profile'),
            preserve_default=False,
        ),
    ]
